### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DarrellMozingo**
### Description

Updates README for formatting & example.

### Issues Resolved

None

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [ ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

Formatting & small example correction.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @DarrellMozingo

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by DarrellMozingo** [comment]
Do I need to sign the CLA for a small readme update?

**Comment by tas50** [comment]
Readme fix falls under the obvious fix policy

**Comment by tas50** [comment]
Thanks for the fix

**Pull request merged**
