### PR TITLE
dropping support for centos 6 in test-kitchen

### PR DESCRIPTION
**Pull request by chasebolt**
removing references for my sanity that centos 6 no longer is supported.

https://github.com/docker/docker/issues/14174#issuecomment-118169576

### CODE REVIEW

**Comment by someara** [comment]
unfortunately I'm gonna have to close this ;)

**Comment by chasebolt** [comment]
lol wha?? Why no reason on not merging this in?

**Comment by chasebolt** [comment]
Are you able to actually get this to work with centos 6 in test-kitchen? I've had no luck making it work.

**Comment by someara** [comment]
Yep. I just fixed up the sysvinit stuff as well.

**Comment by someara** [comment]
Aha... I see what was going on... I was using Digital Ocean to test centos6
and they have a modern kernel.
It fails with Vagrant.

one sec...

**Comment by someara** [comment]
aaand it's gone from .kitchen.yml

**Comment by chasebolt** [comment]
Hahaha ok then! ;)

**Comment by chasebolt** [comment]
README testing matrix please :)

**Pull request closed without merging**
