### PR TITLE
Remove support for Precise and Vivid

### PR DESCRIPTION
**Pull request by tas50**
These are both EOL and have old kernsl. Let them die

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by someara** [comment]
Gotta keep Presicse

**Comment by tas50** [comment]
It's EOL and not getting security updates anymore.

**Comment by someara** [comment]
It gets security updates into 2019 through Extended Security Maintenance.
Docker explicitly publishes precise packages, which will work by installing a modern kernel from backports.

-s

**Comment by chasebolt** [comment]
the new docker repos, which i have been switching everything over to, no longer supports precise and vivid. https://download.docker.com/linux/ubuntu/dists/

i think we should drop support as it will make testing more difficult and i dont even want to think about the feature support once i get this library up to date with all the new docker features.

**Comment by chasebolt** [comment]
ok ill keep the helper logic for precise. imo, if someone is going through all the effort in still using precise with a newer docker cookbook, they really should be using the `package_name` and `package_version` properties.

**Comment by someara** [comment]
I resemble that remark!

**Comment by chasebolt** [comment]
vivid has been removed. keeping precise until someone *cough* @someara *cough* upgrades a few systems.

**Pull request closed without merging**
