### PR TITLE
Add Ubuntu 16.04 Xenial to package helper

### PR DESCRIPTION
**Pull request by DavidJFelix**
### Description

Add Ubuntu 16.04 to helper package to begin 16.04 support

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @DavidJFelix

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by chasebolt** [comment]
perfect! can you confirm what is the default version of `docker-engine` from the docker repo on xenial?

this block may need to be updated if it is anything other than v1.10.0
https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_installation_package.rb#L69-L75

**Comment by DavidJFelix** [comment]
@chasebolt Per https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/filelist, it is 1.11

It seems like much of that block needs to be updated. I can do it.

**Comment by DavidJFelix** [comment]
@chasebolt I held off on editing the other portions of the file, since I don't think they pertain to this pull request. I was intending on removing Ubuntu Vivid support (as Unicorn appears to have been) since it's no longer listed on the [Active Releases Page](https://wiki.ubuntu.com/Releases)

**Comment by chasebolt** [comment]
feel free to update the `version_string` and `default_docker_version` blocks 😃

**Comment by DavidJFelix** [comment]
@chasebolt should be up to date now. I don't think there's anything remaining in the `version_string` block.

**Pull request merged**
