### PR TITLE
Removes vendored gems in favor of chef_gem install

### LINKED ISSUE #649: Vendoring excon gem breaks with chef-dk
The way this cookbook load the excon gem, causes it to be loaded twice if you're using chef-dk, or i you have the gem in your system ruby install, which leads to break all the alias_method that are used in excon, and it makes it calls recursively, leading to a stack level too deep error.

Any ideas on how to fix this issue?

### PR DESCRIPTION
**Pull request by kri5**
This should fix #649.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @kri5

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chasebolt** [comment]
good work on this :+1: ! we've been looking for a solution to this for awhile. test-kitchen ran beautifully on your branch.

if you can just get the travis-ci cops failures corrected and sign the CLA next that would be awesome

**Comment by kri5** [comment]
@chasebolt Thanks

The main issue with travis-ci cops failure seems due to the fact that ChefSpec loads all the ruby files in the libraries folders, before having a noderunner, there were an issue filled in there https://github.com/sethvargo/chefspec/pull/394 about the same issue.

Do you have any ideas about that?

Btw i'll take a look a the rubocop warnings to fix them

**Comment by chasebolt** [comment]
@kri5 have you signed the CLA yet? I have a version based off of your branch that fixes chefspec; once we get you signed and this merged in I can submit the PR.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by kri5** [comment]
@chasebolt Done

**Pull request merged**
