### PR TITLE
adding systemd_socket_opts to allow including additional params

### PR DESCRIPTION
**Pull request by chasebolt**

### CODE REVIEW

**Comment by docwhat** [comment]
@chasebolt

You have a typo in the template for the socket:

``` patch
diff --git a/templates/default/systemd/docker.socket-override.erb b/templates/default/systemd/docker.socket-override.erb
index 9356d7f..d7381f6 100644
--- a/templates/default/systemd/docker.socket-override.erb
+++ b/templates/default/systemd/docker.socket-override.erb
@@ -7,7 +7,7 @@ ListenStream=<%= @docker_socket %>
 SocketMode=0660
 SocketUser=root
 SocketGroup=<%= @config.group %>
-<%= @systemd_args  %>
+<%= @systemd_socket_args  %>
 
 [Install]
 WantedBy=sockets.target

```

**Comment by chasebolt** [comment]
ty

**Comment by docwhat** [comment]
So it looks like I _can't_ override any attributes already set.  Example:

``` init
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker
SocketUser=dill


[Install]
WantedBy=sockets.target
```

This doesn't change the `SocketUser` to `dill`... it remains stuck at `root`:

``` sh
# ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 Feb  1 22:08 /var/run/docker.sock
```

**Comment by docwhat** [comment]
If the `/etc/systemd/system/docker.socket` file didn't exist at all (my original #1058) then I could use `/etc/systemd/system/docker.socket.d/override.conf` to override settings from `/lib/systemd/system/docker.socket`.

**Comment by chasebolt** [comment]
are you trying to change `ListenStream` or just the `SocketUser`?

**Comment by docwhat** [comment]
>are you trying to change `ListenStream` or just the `SocketUser`?

@chasebolt `SocketUser` and `SocketGroup` (though that can be changed via an attribute). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chasebolt** [comment]
released in `v4.9.1`

**Pull request merged**
