### PR TITLE
docker tag force as property

### PR DESCRIPTION
**Pull request by bahchis**
I had an use case in which I need the image retagged.
I could not delete the old tag before hand since the container is supposed to remain running, the resource retags with force as default but there is a hardcoded line which returns if the to_repo already exists.

Removed the return line in case of to_repo exists and create a property to specify force to retag even if exists.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @bahchis

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by bahchis** [comment]
Hi @chasebolt, I have added back the return statement with the force == false.

Thanks.

**Comment by chasebolt** [comment]
👍

**Comment by someara** [comment]
Hi Sergey!

Like a lot of Apache2 licensed projects we require you to sign a CLA before accepting PRs.
Would you mind signing it? https://supermarket.chef.io/become-a-contributor

Thanks!

-s

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by bahchis** [comment]
Hi @someara ,
Friendly bot approved.

Thanks.

**Comment by someara** [comment]
released in 2.4.19

**Pull request merged**
