### PR TITLE
add env_file back into docker_container fixes #872

### LINKED ISSUE #872: [QUESTION] docker env_file
Does this cookbook support the docker `env_file` parameter?

### PR DESCRIPTION
**Pull request by enkaskal**

### CODE REVIEW

**Comment by chasebolt** [comment]
docker run has a —env-file, we would want to pass that through the config json instead of reading in a file and passing individual variables.

**Comment by enkaskal** [comment]
@chasebolt, I thought this cookbook was refactored away from shelling out to `docker run` with the 1.x rewrite. Further, I looked through https://github.com/swipely/docker-api and https://docs.docker.com/engine/api/v1.32/#operation/ContainerCreate and I don't see support for EnvFile. Can you please point me in the right direction?

**Comment by enkaskal** [comment]
accidentally closed earlier when commenting and one of the tests failed because the node couldn't receive a key from ubuntu's keyserver. therefore, closing and reopening again as advised by: https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit/18252580

**Comment by chasebolt** [comment]
released `env_file` support in v2.16.1

**Pull request closed without merging**
