### PR TITLE
allow configuring reload signal #1089

### LINKED ISSUE #1089: Tiny feature request, ability to configure reload signal
Hi,

Would it be possible to add an ability to configure the reload signal? eg. `reload_signal` like it's possible to configure the `signal` for "kill". Currently it's hardcoded here:

https://github.com/chef-cookbooks/docker/blob/8a323a346e9d5f301342de82ad4ef3c55c179266/libraries/docker_container.rb#L646

But for some containers, eg. PHP-FPM containers the process needs a `USR2` signal to reload configuration changes, and not `SIGHUP`.

Thanks.

### PR DESCRIPTION
**Pull request by scalp42**
### Description

Allow overriding `SIGHUP` on container `reload` action.

### Issues Resolved

#1089

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
Thanks @scalp42

**Comment by urlund** [comment]
Hi @dheerajd-msys (and @scalp42 @tas50),

I finally had a chance to get my cookbooks updated, to test this feature, but it seems something is missing for this fix, when I configure reload_signal, and run chef, my container gets restarted every time.

Like this:

```
  * docker_container[my_php] action run
    - stopping my_php
    - deleting my_php
    - update my_php
    -   set reload_signal to "USR2" (was "SIGHUP")
    - starting my_php```
  
Is this a bug, or am I missing something?

Merry X-mas btw 🎄 😃

**Comment by ramereth** [comment]
@urlund can you please provide some sample chef code we can use to confirm this ourselves?

**Comment by urlund** [comment]
@ramereth sure! here you go :)

**my recipe**

```
#
# Cookbook:: test
# Recipe:: php
#

# ...
docker_image "php:8.0-fpm" do
    action :pull_if_missing
    repo   "php"
    tag    "8.0-fpm"
end

# ...
docker_container "php" do
    action  :run
    repo    "php"
    tag     "8.0-fpm"
    reload_signal "USR2"
end
```

**first run:**

```
Starting Chef Infra Client, version 16.8.14
Patents: https://www.chef.io/patents
resolving cookbooks for run list: ["test::php"]
Synchronizing Cookbooks:
  - docker (7.2.2)
  - test (1.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: test::php
  * docker_image[php:8.0-fpm] action pull_if_missing (up to date)
  * docker_container[php] action run
    - create php
    -   set repo                        to "php"
    -   set tag                         to "8.0-fpm"
    -   set command                     to nil (default value)
    -   set cap_add                     to nil (default value)
    -   set cap_drop                    to nil (default value)
    -   set cgroup_parent               to "" (default value)
    -   set cpus                        to 0 (default value)
    -   set cpu_shares                  to 0 (default value)
    -   set cpuset_cpus                 to "" (default value)
    -   set devices                     to [] (default value)
    -   set dns                         to [] (default value)
    -   set dns_search                  to [] (default value)
    -   set domain_name                 to "" (default value)
    -   set entrypoint                  to nil (default value)
    -   set env                         to [] (default value)
    -   set extra_hosts                 to nil (default value)
    -   set exposed_ports               to {} (default value)
    -   set health_check                to {} (default value)
    -   set hostname                    to nil (default value)
    -   set ipc_mode                    to "shareable" (default value)
    -   set kernel_memory               to 0 (default value)
    -   set labels                      to {} (default value)
    -   set links                       to nil (default value)
    -   set init                        to nil (default value)
    -   set ip_address                  to nil (default value)
    -   set mac_address                 to nil (default value)
    -   set memory                      to 0 (default value)
    -   set memory_swap                 to nil (default value)
    -   set memory_swappiness           to 0 (default value)
    -   set memory_reservation          to 0 (default value)
    -   set network_disabled            to false (default value)
    -   set network_mode                to "bridge" (default value)
    -   set network_aliases             to [] (default value)
    -   set oom_kill_disable            to false (default value)
    -   set oom_score_adj               to -500 (default value)
    -   set outfile                     to nil (default value)
    -   set port_bindings               to {} (default value)
    -   set pid_mode                    to "" (default value)
    -   set privileged                  to false (default value)
    -   set publish_all_ports           to false (default value)
    -   set reload_signal               to "USR2"
    -   set remove_volumes              to false (default value)
    -   set restart_maximum_retry_count to 0 (default value)
    -   set restart_policy              to nil (default value)
    -   set runtime                     to "runc" (default value)
    -   set ro_rootfs                   to false (default value)
    -   set security_opt                to nil (default value)
    -   set shm_size                    to 67108864 (default value)
    -   set signal                      to "SIGTERM" (default value)
    -   set sysctls                     to {} (default value)
    -   set tty                         to false (default value)
    -   set ulimits                     to nil (default value)
    -   set user                        to "" (default value)
    -   set userns_mode                 to "" (default value)
    -   set uts_mode                    to "" (default value)
    -   set volumes                     to {} (default value)
    -   set volumes_from                to nil (default value)
    -   set volume_driver               to nil (default value)
    -   set working_dir                 to nil (default value)
    -   set volumes_binds               to nil (default value)
    - starting php

Running handlers:
Running handlers complete
Chef Infra Client finished, 1/2 resources updated in 01 seconds
```

**following runs:**

```
Starting Chef Infra Client, version 16.8.14
Patents: https://www.chef.io/patents
resolving cookbooks for run list: ["test::php"]
Synchronizing Cookbooks:
  - test (1.0.0)
  - docker (7.2.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: test::php
  * docker_image[php:8.0-fpm] action pull_if_missing (up to date)
  * docker_container[php] action run
    - stopping php
    - deleting php
    - update php
    -   set reload_signal to "USR2" (was "SIGHUP")
    - starting php

Running handlers:
Running handlers complete
Chef Infra Client finished, 1/2 resources updated in 02 seconds
```

**Comment by urlund** [comment]
@ramereth Another observation, this is also an issue when setting `cpus` to any other value than the default (0).

First run:

```
  * docker_container[php] action run
    - create php
    ...
    -   set cpus                        to 1000000000
    ...
    - starting php
```

Every run after that:

```
  * docker_container[php] action run
    - stopping php
    - deleting php
    - update php
    -   set cpus to 1000000000 (was 0)
    - starting php
```

My resource:

```
# ...
docker_container "php" do
    action  :run
    repo    "php"
    tag     "8.0-fpm"
    cpus   1
end
```

**Comment by urlund** [comment]
@ramereth ... maybe a separate issue/bug report should be created for this, since it's not just related to the pull request anymore 😄 ?

**Comment by ramereth** [comment]
@urlund yes please

**Comment by urlund** [comment]
@ramereth I made this instead of a new issue:

https://github.com/sous-chefs/docker/pull/1152

**Pull request merged**
